<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Form Manifest - {{ $booking->booking_code }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style>
        * { font-family: 'Nunito', sans-serif; }
        .bg-green-gradient { background: linear-gradient(135deg, #2E7D32, #4CAF50); }
        .tab-active { @apply border-green-500 text-green-600 bg-green-50; }
        .tab-inactive { @apply border-transparent text-gray-600 hover:text-gray-900 hover:bg-gray-50; }
        .tab-content { display: none; }
        .tab-content.active { display: block; animation: fadeIn 0.3s ease-in; }
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
    </style>
</head>
<body class="bg-gray-50">
    <div class="max-w-6xl mx-auto py-8 px-4">
        
        <!-- Header -->
        <div class="bg-white rounded-2xl shadow-lg overflow-hidden mb-6">
            <div class="bg-green-gradient text-white p-6">
                <div class="flex items-center justify-between">
                    <div>
                        <img src="{{ url('WEB_HMTour/wp-content/uploads/2023/04/Logo-HM_UMRAH-3-WHITE.png') }}" 
                             alt="HM Tour" class="h-10 w-auto object-contain mb-2" 
                             onerror="this.style.display='none'">
                        <h1 class="text-2xl font-black">Form Manifest Jamaah</h1>
                        <p class="text-green-100 text-sm mt-1">Lengkapi data perjalanan untuk {{ $booking->getTotalPax() }} jamaah</p>
                    </div>
                    <div class="text-right">
                        <div class="text-xl font-black">{{ $booking->booking_code }}</div>
                        <div class="text-green-200 text-xs mt-1">{{ $booking->travelPackage->package_name ?? 'Paket Travel' }}</div>
                    </div>
                </div>
            </div>

            <!-- Success Message -->
            @if(session('success'))
            <div class="bg-green-50 border-l-4 border-green-500 p-4 m-6">
                <div class="flex items-center">
                    <i class='bx bx-check-circle text-2xl text-green-500 mr-3'></i>
                    <p class="text-green-700 font-semibold">{{ session('success') }}</p>
                </div>
            </div>
            @endif

            <!-- Error Message -->
            @if(session('error'))
            <div class="bg-red-50 border-l-4 border-red-500 p-4 m-6">
                <div class="flex items-center">
                    <i class='bx bx-error-circle text-2xl text-red-500 mr-3'></i>
                    <p class="text-red-700 font-semibold">{{ session('error') }}</p>
                </div>
            </div>
            @endif

            <!-- Info Box -->
            <div class="bg-blue-50 border-2 border-blue-200 rounded-xl p-4 m-6">
                <div class="flex items-start gap-3">
                    <i class='bx bx-info-circle text-2xl text-blue-600 flex-shrink-0'></i>
                    <div class="text-sm text-blue-800">
                        <p class="font-bold mb-1">📸 Fitur OCR Tersedia!</p>
                        <p>Upload foto KTP dan Passport, sistem kami akan otomatis membaca dan mengisi data. Data dapat disimpan bertahap dan dilanjutkan kemudian.</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Tab Navigation -->
        <div class="bg-white rounded-2xl shadow-lg overflow-hidden mb-6">
            <div class="flex overflow-x-auto border-b border-gray-200" id="tabNavigation">
                <!-- Tabs will be generated by JavaScript -->
            </div>
        </div>

        <!-- Tab Content Container -->
        <div class="bg-white rounded-2xl shadow-lg overflow-hidden p-6">
            <div id="tabContentContainer">
                <!-- Tab contents will be generated by JavaScript -->
            </div>
        </div>

        <!-- Save Button (Outside Tab Content) -->
        <div class="bg-white rounded-2xl shadow-lg overflow-hidden p-6 mt-6">
            <div class="flex gap-3">
                <button type="button" onclick="saveAllData()" 
                        class="flex-1 bg-green-gradient text-white font-bold py-4 rounded-xl hover:shadow-lg transition-all flex items-center justify-center gap-2">
                    <i class='bx bx-save text-2xl'></i>
                    <span>Simpan Semua Data</span>
                </button>
            </div>
            
            <div class="bg-gray-50 rounded-xl p-4 text-sm text-gray-600 mt-4">
                <p class="font-semibold mb-1">📝 Catatan:</p>
                <ul class="list-disc list-inside space-y-1 text-xs">
                    <li>Dokumen bertanda <span class="text-red-500">*</span> wajib diisi</li>
                    <li>Data dapat disimpan bertahap dan dilanjutkan kemudian</li>
                    <li>Pastikan foto jelas dan tidak blur untuk hasil OCR terbaik</li>
                    <li>Klik tab untuk berpindah antar jamaah</li>
                </ul>
            </div>
        </div>

        <!-- Footer -->
        <div class="text-center mt-6 text-sm text-gray-500">
            <p>&copy; {{ date('Y') }} HM Tour & Travel. Berizin Kemenag RI.</p>
        </div>

    </div>

    <script>
        // Data from Laravel
        const booking = @json($booking);
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        
        // State
        let currentTab = 0;
        let jamaahData = [];
        
        // Initialize
        document.addEventListener('DOMContentLoaded', function() {
            initializeJamaahData();
            renderTabs();
            renderAllTabContents();
            loadSavedData();
        });

        function initializeJamaahData() {
            // Main jamaah
            jamaahData.push({
                index: 0,
                nama: booking.jamaah?.nama || 'Jamaah Utama',
                tanggal_lahir: booking.jamaah?.ktp_tanggal_lahir || booking.jamaah?.passport_tanggal_lahir || null,
                isMain: true,
                data: {}
            });

            // Family members - Get from booking.family_members_booking
            console.log('Booking data:', booking);
            console.log('Family members from booking:', booking.family_members_booking);
            
            let familyMembers = booking.family_members_booking;
            
            // Parse if string
            if (typeof familyMembers === 'string') {
                try {
                    familyMembers = JSON.parse(familyMembers);
                    console.log('Parsed family members:', familyMembers);
                } catch (e) {
                    console.error('Failed to parse family_members_booking:', e);
                    familyMembers = [];
                }
            }
            
            // Add family members
            if (Array.isArray(familyMembers) && familyMembers.length > 0) {
                familyMembers.forEach((member, idx) => {
                    jamaahData.push({
                        index: idx + 1,
                        nama: member.nama || `Anggota Keluarga ${idx + 1}`,
                        tanggal_lahir: member.tanggal_lahir || null,
                        isMain: false,
                        data: {}
                    });
                });
                console.log('Total jamaah after adding family:', jamaahData.length);
            } else {
                console.log('No family members found or not an array');
            }
        }

        function renderTabs() {
            const tabNav = document.getElementById('tabNavigation');
            tabNav.innerHTML = jamaahData.map((jamaah, idx) => `
                <button type="button" 
                        onclick="switchTab(${idx})"
                        id="tab-${idx}"
                        class="flex-shrink-0 px-6 py-4 border-b-2 font-semibold text-sm transition-colors ${idx === 0 ? 'tab-active' : 'tab-inactive'}">
                    <div class="flex items-center gap-2">
                        <span>${jamaah.nama}</span>
                        <span id="badge-${idx}" class="inline-flex items-center justify-center w-6 h-6 text-xs font-bold rounded-full bg-red-500 text-white">
                            8
                        </span>
                    </div>
                </button>
            `).join('');
        }

        function switchTab(index) {
            // Save current tab data before switching
            saveCurrentTabData(false); // false = don't show alert
            
            // Update tab styles
            jamaahData.forEach((_, idx) => {
                const tab = document.getElementById(`tab-${idx}`);
                const content = document.getElementById(`tab-content-${idx}`);
                
                if (idx === index) {
                    tab.className = tab.className.replace('tab-inactive', 'tab-active');
                    if (content) content.classList.add('active');
                } else {
                    tab.className = tab.className.replace('tab-active', 'tab-inactive');
                    if (content) content.classList.remove('active');
                }
            });

            currentTab = index;
        }

        function calculateAge(tanggalLahir) {
            if (!tanggalLahir) return null;
            const today = new Date();
            const birthDate = new Date(tanggalLahir);
            let age = today.getFullYear() - birthDate.getFullYear();
            const monthDiff = today.getMonth() - birthDate.getMonth();
            if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
                age--;
            }
            return age;
        }

        function renderAllTabContents() {
            const container = document.getElementById('tabContentContainer');
            container.innerHTML = jamaahData.map((jamaah, index) => {
                const age = calculateAge(jamaah.tanggal_lahir);
                const isChild = age !== null && age < 17;
                
                return `
                <div id="tab-content-${index}" class="tab-content ${index === 0 ? 'active' : ''}">
                    ${generateTabContentHTML(index, jamaah, age, isChild)}
                </div>
                `;
            }).join('');
            
            // Load saved data for all tabs
            jamaahData.forEach((_, idx) => loadTabData(idx));
        }

        function generateTabContentHTML(index, jamaah, age, isChild) {
            return `
                <div id="manifestForm-${index}" class="space-y-6">
                    <input type="hidden" name="jamaah_index" value="${index}">
                    
                    <!-- Passport Section -->
                    <div class="border-2 border-gray-200 rounded-xl p-6">
                        <h3 class="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                            <i class='bx bx-book text-green-600'></i>
                            Passport <span class="text-red-500">*</span>
                        </h3>
                        
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div class="md:col-span-2">
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Upload Foto Passport</label>
                                <div class="border-2 border-dashed border-gray-300 rounded-lg p-4 text-center hover:border-green-500 transition-all">
                                    <input type="file" id="passport_foto_${index}" accept="image/*" class="hidden" onchange="handlePassportUpload(${index}, this)">
                                    <label for="passport_foto_${index}" class="cursor-pointer">
                                        <div id="passport_preview_${index}">
                                            <i class='bx bx-cloud-upload text-4xl text-gray-400'></i>
                                            <div class="text-sm font-semibold text-gray-700 mt-2">Klik untuk upload</div>
                                            <div class="text-xs text-gray-500">JPG, PNG (Max 5MB)</div>
                                        </div>
                                    </label>
                                </div>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Nomor Passport *</label>
                                <input type="text" id="passport_nomor_${index}" required
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500"
                                       placeholder="A1234567">
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Nama di Passport</label>
                                <input type="text" id="passport_nama_${index}"
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500"
                                       placeholder="Sesuai passport">
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Tanggal Lahir</label>
                                <input type="date" id="passport_tanggal_lahir_${index}"
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500">
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Tanggal Kadaluarsa *</label>
                                <input type="date" id="passport_tanggal_kadaluarsa_${index}" required
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500">
                            </div>
                            
                            <div class="md:col-span-2">
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Kewarganegaraan</label>
                                <input type="text" id="passport_kewarganegaraan_${index}" value="Indonesia"
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500">
                            </div>
                        </div>
                    </div>

                    <!-- KTP Section (Hidden for children < 17 years) -->
                    ${isChild ? `
                    <div class="bg-blue-50 border-2 border-blue-200 rounded-xl p-4">
                        <div class="flex items-start gap-3">
                            <i class='bx bx-info-circle text-2xl text-blue-600 flex-shrink-0'></i>
                            <div class="text-sm text-blue-800">
                                <p class="font-bold mb-1">ℹ️ Informasi Anak Dibawah 17 Tahun</p>
                                <p>Jamaah ini berusia <strong>${age} tahun</strong>. Untuk anak dibawah 17 tahun, <strong>KTP tidak diperlukan</strong>. Silakan upload <strong>Akta Lahir</strong> sebagai gantinya.</p>
                            </div>
                        </div>
                    </div>
                    ` : ''}
                    
                    <div class="border-2 border-gray-200 rounded-xl p-6 ${isChild ? 'hidden' : ''}" id="ktp_section_${index}">
                        <h3 class="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                            <i class='bx bx-id-card text-green-600'></i>
                            KTP <span class="text-red-500">*</span>
                        </h3>
                        
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div class="md:col-span-2">
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Upload Foto KTP</label>
                                <div class="border-2 border-dashed border-gray-300 rounded-lg p-4 text-center hover:border-green-500 transition-all">
                                    <input type="file" id="ktp_foto_${index}" accept="image/*" class="hidden" onchange="handleKtpUpload(${index}, this)">
                                    <label for="ktp_foto_${index}" class="cursor-pointer">
                                        <div id="ktp_preview_${index}">
                                            <i class='bx bx-cloud-upload text-4xl text-gray-400'></i>
                                            <div class="text-sm font-semibold text-gray-700 mt-2">Klik untuk upload</div>
                                            <div class="text-xs text-gray-500">JPG, PNG (Max 5MB)</div>
                                        </div>
                                    </label>
                                </div>
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">NIK (16 digit) *</label>
                                <input type="text" id="ktp_nik_${index}" maxlength="16" pattern="\\d{16}" ${isChild ? '' : 'required'}
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500"
                                       placeholder="16 digit angka">
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Nama di KTP</label>
                                <input type="text" id="ktp_nama_${index}"
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500">
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Tempat Lahir</label>
                                <input type="text" id="ktp_tempat_lahir_${index}"
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500">
                            </div>
                            
                            <div>
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Tanggal Lahir</label>
                                <input type="date" id="ktp_tanggal_lahir_${index}"
                                       class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500">
                            </div>
                            
                            <div class="md:col-span-2">
                                <label class="block text-sm font-semibold text-gray-700 mb-2">Alamat KTP</label>
                                <textarea id="ktp_alamat_${index}" rows="2"
                                          class="w-full border-2 border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-green-500"></textarea>
                            </div>
                        </div>
                    </div>

                    <!-- Additional Documents -->
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <!-- Pas Foto 4x6 (Optional) -->
                        <div class="border-2 border-gray-200 rounded-xl p-4">
                            <h4 class="font-bold text-gray-900 mb-3 flex items-center gap-2">
                                <i class='bx bx-user-circle text-green-600'></i>
                                Pas Foto 4x6 <span class="text-gray-500">(opsional)</span>
                            </h4>
                            <input type="file" id="pas_foto_${index}" accept="image/*" class="text-sm">
                        </div>

                        <!-- Kartu Keluarga -->
                        <div class="border-2 border-gray-200 rounded-xl p-4">
                            <h4 class="font-bold text-gray-900 mb-3 flex items-center gap-2">
                                <i class='bx bx-group text-green-600'></i>
                                Kartu Keluarga <span class="text-red-500">*</span>
                            </h4>
                            <input type="file" id="kartu_keluarga_${index}" accept="image/*" class="text-sm">
                        </div>

                        <!-- Buku Nikah -->
                        <div class="border-2 border-gray-200 rounded-xl p-4">
                            <h4 class="font-bold text-gray-900 mb-3 flex items-center gap-2">
                                <i class='bx bx-book-heart text-green-600'></i>
                                Buku Nikah <span class="text-yellow-500">(jika menikah)</span>
                            </h4>
                            <input type="file" id="buku_nikah_${index}" accept="image/*" class="text-sm">
                        </div>

                        <!-- Akta Lahir (Only for children < 17 years) -->
                        ${isChild ? `
                        <div class="border-2 border-gray-200 rounded-xl p-4">
                            <h4 class="font-bold text-gray-900 mb-3 flex items-center gap-2">
                                <i class='bx bx-file text-green-600'></i>
                                Akta Lahir <span class="text-red-500">*</span>
                            </h4>
                            <input type="file" id="akta_lahir_${index}" accept="image/*" class="text-sm" required>
                            <p class="text-xs text-blue-600 mt-1">⚠️ Wajib untuk anak dibawah 17 tahun</p>
                        </div>
                        ` : ''}

                        <!-- Vaksin Meningitis -->
                        <div class="border-2 border-gray-200 rounded-xl p-4">
                            <h4 class="font-bold text-gray-900 mb-3 flex items-center gap-2">
                                <i class='bx bx-injection text-green-600'></i>
                                Buku Kuning Vaksin <span class="text-gray-500">(opsional)</span>
                            </h4>
                            <input type="file" id="vaksin_meningitis_${index}" accept="image/*" class="text-sm">
                        </div>

                        <!-- BPJS -->
                        <div class="border-2 border-gray-200 rounded-xl p-4">
                            <h4 class="font-bold text-gray-900 mb-3 flex items-center gap-2">
                                <i class='bx bx-card text-green-600'></i>
                                BPJS/KIS/ASKES <span class="text-gray-500">(opsional)</span>
                            </h4>
                            <input type="file" id="bpjs_${index}" accept="image/*" class="text-sm">
                        </div>
                    </div>

                </div>
            `;

            `;
        }

        function handlePassportUpload(index, input) {
            if (!input.files || !input.files[0]) return;
            
            const file = input.files[0];
            const preview = document.getElementById(`passport_preview_${index}`);
            
            preview.innerHTML = `
                <i class='bx bx-loader-alt bx-spin text-4xl text-blue-500'></i>
                <div class="text-sm font-semibold text-blue-700 mt-2">Memproses OCR...</div>
            `;

            const formData = new FormData();
            formData.append('passport_image', file);

            fetch('{{ route("public.manifest.ocr-passport") }}', {
                method: 'POST',
                headers: { 'X-CSRF-TOKEN': csrfToken },
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    document.getElementById(`passport_nomor_${index}`).value = data.data.passport_nomor || '';
                    document.getElementById(`passport_nama_${index}`).value = data.data.passport_nama || '';
                    document.getElementById(`passport_tanggal_lahir_${index}`).value = data.data.passport_tanggal_lahir || '';
                    document.getElementById(`passport_tanggal_kadaluarsa_${index}`).value = data.data.passport_tanggal_kadaluarsa || '';
                    document.getElementById(`passport_kewarganegaraan_${index}`).value = data.data.passport_kewarganegaraan || 'Indonesia';
                    
                    preview.innerHTML = `
                        <i class='bx bx-check-circle text-4xl text-green-500'></i>
                        <div class="text-sm font-semibold text-green-700 mt-2">✅ OCR Berhasil!</div>
                    `;
                } else {
                    throw new Error('OCR failed');
                }
            })
            .catch(error => {
                preview.innerHTML = `
                    <i class='bx bx-error-circle text-4xl text-yellow-500'></i>
                    <div class="text-sm font-semibold text-yellow-700 mt-2">⚠️ OCR gagal, isi manual</div>
                `;
            });
        }

        function handleKtpUpload(index, input) {
            if (!input.files || !input.files[0]) return;
            
            const file = input.files[0];
            const preview = document.getElementById(`ktp_preview_${index}`);
            
            preview.innerHTML = `
                <i class='bx bx-loader-alt bx-spin text-4xl text-blue-500'></i>
                <div class="text-sm font-semibold text-blue-700 mt-2">Memproses OCR...</div>
            `;

            const formData = new FormData();
            formData.append('ktp_image', file);

            fetch('{{ route("public.manifest.ocr-ktp") }}', {
                method: 'POST',
                headers: { 'X-CSRF-TOKEN': csrfToken },
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    document.getElementById(`ktp_nik_${index}`).value = data.data.ktp_nik || '';
                    document.getElementById(`ktp_nama_${index}`).value = data.data.ktp_nama || '';
                    document.getElementById(`ktp_tempat_lahir_${index}`).value = data.data.ktp_tempat_lahir || '';
                    document.getElementById(`ktp_tanggal_lahir_${index}`).value = data.data.ktp_tanggal_lahir || '';
                    document.getElementById(`ktp_alamat_${index}`).value = data.data.ktp_alamat || '';
                    
                    preview.innerHTML = `
                        <i class='bx bx-check-circle text-4xl text-green-500'></i>
                        <div class="text-sm font-semibold text-green-700 mt-2">✅ OCR Berhasil!</div>
                    `;
                } else {
                    throw new Error('OCR failed');
                }
            })
            .catch(error => {
                preview.innerHTML = `
                    <i class='bx bx-error-circle text-4xl text-yellow-500'></i>
                    <div class="text-sm font-semibold text-yellow-700 mt-2">⚠️ OCR gagal, isi manual</div>
                `;
            });
        }

        function saveCurrentTabData(showAlert = true) {
            const index = currentTab;
            const data = {
                passport_nomor: document.getElementById(`passport_nomor_${index}`)?.value || '',
                passport_nama: document.getElementById(`passport_nama_${index}`)?.value || '',
                passport_tanggal_lahir: document.getElementById(`passport_tanggal_lahir_${index}`)?.value || '',
                passport_tanggal_kadaluarsa: document.getElementById(`passport_tanggal_kadaluarsa_${index}`)?.value || '',
                passport_kewarganegaraan: document.getElementById(`passport_kewarganegaraan_${index}`)?.value || '',
                ktp_nik: document.getElementById(`ktp_nik_${index}`)?.value || '',
                ktp_nama: document.getElementById(`ktp_nama_${index}`)?.value || '',
                ktp_tempat_lahir: document.getElementById(`ktp_tempat_lahir_${index}`)?.value || '',
                ktp_tanggal_lahir: document.getElementById(`ktp_tanggal_lahir_${index}`)?.value || '',
                ktp_alamat: document.getElementById(`ktp_alamat_${index}`)?.value || '',
                akta_lahir: document.getElementById(`akta_lahir_${index}`)?.files?.[0]?.name || '',
            };

            jamaahData[index].data = data;
            localStorage.setItem(`manifest_${booking.id}_${index}`, JSON.stringify(data));
            
            updateBadge(index);
            
            if (showAlert) {
                alert('✅ Data berhasil disimpan!');
            }
        }

        function saveAllData() {
            // Save all tabs
            jamaahData.forEach((_, idx) => {
                const data = {
                    passport_nomor: document.getElementById(`passport_nomor_${idx}`)?.value || '',
                    passport_nama: document.getElementById(`passport_nama_${idx}`)?.value || '',
                    passport_tanggal_lahir: document.getElementById(`passport_tanggal_lahir_${idx}`)?.value || '',
                    passport_tanggal_kadaluarsa: document.getElementById(`passport_tanggal_kadaluarsa_${idx}`)?.value || '',
                    passport_kewarganegaraan: document.getElementById(`passport_kewarganegaraan_${idx}`)?.value || '',
                    ktp_nik: document.getElementById(`ktp_nik_${idx}`)?.value || '',
                    ktp_nama: document.getElementById(`ktp_nama_${idx}`)?.value || '',
                    ktp_tempat_lahir: document.getElementById(`ktp_tempat_lahir_${idx}`)?.value || '',
                    ktp_tanggal_lahir: document.getElementById(`ktp_tanggal_lahir_${idx}`)?.value || '',
                    ktp_alamat: document.getElementById(`ktp_alamat_${idx}`)?.value || '',
                    akta_lahir: document.getElementById(`akta_lahir_${idx}`)?.files?.[0]?.name || '',
                };

                jamaahData[idx].data = data;
                localStorage.setItem(`manifest_${booking.id}_${idx}`, JSON.stringify(data));
                updateBadge(idx);
            });
            
            alert('✅ Semua data berhasil disimpan! Terima kasih.');
            // TODO: Submit all data to server
        }

        function loadSavedData() {
            jamaahData.forEach((jamaah, idx) => {
                const saved = localStorage.getItem(`manifest_${booking.id}_${idx}`);
                if (saved) {
                    jamaah.data = JSON.parse(saved);
                }
            });
        }

        function loadTabData(index) {
            const data = jamaahData[index].data;
            if (!data) return;

            Object.keys(data).forEach(key => {
                const element = document.getElementById(`${key}_${index}`);
                if (element && data[key]) {
                    element.value = data[key];
                }
            });
        }

        function updateBadge(index) {
            const data = jamaahData[index].data || {};
            const jamaah = jamaahData[index];
            const age = calculateAge(jamaah.tanggal_lahir);
            const isChild = age !== null && age < 17;
            
            // Required fields based on age
            let required = ['passport_nomor', 'passport_tanggal_kadaluarsa'];
            
            if (isChild) {
                // Children < 17: Akta Lahir required, KTP not required
                required.push('akta_lahir');
            } else {
                // Adults >= 17: KTP required, Akta Lahir optional
                required.push('ktp_nik');
            }
            
            // Count missing required fields
            const missing = required.filter(field => !data[field]).length;
            
            const badge = document.getElementById(`badge-${index}`);
            if (missing === 0) {
                badge.className = 'inline-flex items-center justify-center w-6 h-6 text-xs font-bold rounded-full bg-green-500 text-white';
                badge.innerHTML = '✓';
            } else {
                badge.className = 'inline-flex items-center justify-center w-6 h-6 text-xs font-bold rounded-full bg-red-500 text-white';
                badge.textContent = missing;
            }
        }
    </script>
</body>
</html>
