<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('partnership_programs', function (Blueprint $table) {
            $table->id();
            $table->string('name'); // HM Member, HM Seller, HM Partner, HM Leader, HM Master
            $table->string('slug')->unique();
            $table->text('description')->nullable();
            $table->text('target_audience')->nullable(); // Target audience
            $table->json('benefits')->nullable(); // Array of benefits
            $table->decimal('registration_fee', 15, 2)->default(0); // Biaya pendaftaran
            $table->decimal('min_sale_commission', 15, 2); // Komisi minimal per penjualan
            $table->decimal('default_ppc_commission', 10, 2)->default(50); // Default PPC
            $table->boolean('requires_previous_booking')->default(false); // Untuk HM Member
            $table->boolean('is_active')->default(true);
            $table->integer('sort_order')->default(0);
            $table->timestamps();
        });
        
        // Seed data program kemitraan
        DB::table('partnership_programs')->insert([
            [
                'name' => 'HM Member',
                'slug' => 'hm-member',
                'description' => 'Program khusus alumni jamaah yang sudah pernah order paket sebelumnya. Gratis tanpa biaya pendaftaran.',
                'target_audience' => 'Alumni Jamaah HM Tour',
                'benefits' => json_encode([
                    'Komisi 500ribu-1juta/Pax',
                    'Dashboard Kemitraan',
                    'Link Referral Personal',
                    'Materi Konten Promosi',
                    'Group WA Exclusive',
                    'Product Knowledge',
                    'Full Support CS Pusat',
                    'ID Card Digital',
                    'Diskon Khusus Internal',
                    'Katalog Soft File',
                ]),
                'registration_fee' => 0,
                'min_sale_commission' => 500000,
                'default_ppc_commission' => 50,
                'requires_previous_booking' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HM Seller',
                'slug' => 'hm-seller',
                'description' => 'Program untuk seller pemula yang ingin memulai bisnis travel umrah.',
                'target_audience' => 'Reseller & Affiliate Marketing Resmi',
                'benefits' => json_encode([
                    'Komisi 500ribu-3juta/Pax',
                    'Reward Penjualan Terbaik',
                    'Dashboard Kemitraan',
                    'Sertifikat Agen Resmi',
                    'Materi Konten Promosi',
                    'Group WA Exclusive',
                    'Video Tutorial Keagenan',
                    'Akses Kelas Marketing',
                    'Pelatihan Pelayanan',
                    'File Branding Template',
                    'Diskon Khusus Internal',
                    'Product Knowledge',
                    'Itinerary Soft File',
                    'Katalog Soft File',
                    'Full Support CS Pusat',
                    'ID Card Digital',
                    'Kartu Nama',
                    'Website Landing Page',
                    'Roll Banner Promosi',
                    'Bisa Menjual Paket Shafaq',
                    'Jaringan Kemitraan',
                    'Akses Database & Leads',
                    'Spanduk Kemitraan',
                    'Acrylic Flyer Stand',
                    'Map Invoice HM Tour',
                    'Vest / Rompi HM',
                    'Bisa Buat Paket Customize',
                    'Hak Eksklusif Wilayah',
                    'Tools Marketing',
                    'Event Desk Meja Booth',
                    'Full Perlengkapan Display',
                    'Sistem Management',
                    'Pelatihan Operasional',
                    'Rekomendasi Tour Leader',
                    'Branding Design Kantor',
                    'Dukungan Iklan Berbayar',
                ]),
                'registration_fee' => 1000000,
                'min_sale_commission' => 500000,
                'default_ppc_commission' => 50,
                'requires_previous_booking' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HM Partner',
                'slug' => 'hm-partner',
                'description' => 'Program kemitraan untuk partner yang serius mengembangkan bisnis travel.',
                'target_audience' => 'Public Figur, Komunitas & Instansi',
                'benefits' => json_encode([
                    'Komisi 1Juta-5juta/Pax',
                    'Reward Penjualan Terbaik',
                    'Dashboard Kemitraan',
                    'Sertifikat Agen Resmi',
                    'Materi Konten Promosi',
                    'Group WA Exclusive',
                    'Video Tutorial Keagenan',
                    'Akses Kelas Marketing',
                    'Pelatihan Pelayanan',
                    'File Branding Template',
                    'Diskon Khusus Internal',
                    'Product Knowledge',
                    'Itinerary Soft File & Cetak',
                    'Katalog Soft File & Cetak',
                    'Full Support CS Pusat',
                    'ID Card Digital',
                    'Kartu Nama',
                    'Website Landing Page',
                    'Roll Banner Promosi',
                    'Bisa Menjual Paket Shafaq',
                    'Jaringan Kemitraan',
                    'Akses Database & Leads',
                    'Spanduk Kemitraan',
                    'Acrylic Flyer Stand',
                    'Map Invoice HM Tour',
                    'Vest / Rompi HM',
                    'Bisa Buat Paket Customize',
                    'Hak Eksklusif Wilayah',
                    'Tools Marketing',
                    'Event Desk Meja Booth',
                    'Full Perlengkapan Display',
                    'Sistem Management',
                    'Pelatihan Operasional',
                    'Rekomendasi Tour Leader',
                    'Branding Design Kantor',
                    'Dukungan Iklan Berbayar',
                ]),
                'registration_fee' => 2000000,
                'min_sale_commission' => 1000000,
                'default_ppc_commission' => 50,
                'requires_previous_booking' => false,
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HM Leader',
                'slug' => 'hm-leader',
                'description' => 'Program untuk leader yang ingin membangun tim dan jaringan distribusi.',
                'target_audience' => 'Agen Aktif Resmi',
                'benefits' => json_encode([
                    'Komisi 1,5Juta-7juta/Pax',
                    'Reward Penjualan Terbaik',
                    'Dashboard Kemitraan',
                    'Sertifikat Agen Resmi',
                    'Materi Konten Promosi',
                    'Group WA Exclusive',
                    'Video Tutorial Keagenan',
                    'Akses Kelas Marketing',
                    'Pelatihan Pelayanan',
                    'File Branding Template',
                    'Diskon Khusus Internal',
                    'Product Knowledge',
                    'Itinerary Soft File & Cetak',
                    'Katalog Soft File & Cetak',
                    'Full Support CS Pusat',
                    'ID Card Digital',
                    'Kartu Nama',
                    'Website Landing Page',
                    'Roll Banner Promosi',
                    'Bisa Menjual Paket Shafaq',
                    'Jaringan Kemitraan',
                    'Akses Database & Leads',
                    'Spanduk Kemitraan',
                    'Acrylic Flyer Stand',
                    'Map Invoice HM Tour',
                    'Vest / Rompi HM',
                    'Bisa Buat Paket Customize',
                    'Hak Eksklusif Wilayah',
                    'Tools Marketing',
                    'Event Desk Meja Booth',
                    'Full Perlengkapan Display',
                    'Sistem Management',
                    'Pelatihan Operasional',
                    'Rekomendasi Tour Leader',
                    'Branding Design Kantor',
                    'Dukungan Iklan Berbayar',
                ]),
                'registration_fee' => 4000000,
                'min_sale_commission' => 1500000,
                'default_ppc_commission' => 50,
                'requires_previous_booking' => false,
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HM Master',
                'slug' => 'hm-master',
                'description' => 'Program master untuk affiliator profesional dengan komisi tertinggi.',
                'target_audience' => 'Kantor Cabang Exclusive Kota Besar',
                'benefits' => json_encode([
                    'Komisi 2juta-10juta/Pax',
                    'Reward Penjualan Terbaik',
                    'Dashboard Kemitraan',
                    'Sertifikat Agen Resmi',
                    'Materi Konten Promosi',
                    'Group WA Exclusive',
                    'Video Tutorial Keagenan',
                    'Akses Kelas Marketing',
                    'Pelatihan Pelayanan',
                    'File Branding Template',
                    'Diskon Khusus Internal',
                    'Product Knowledge',
                    'Itinerary Soft File & Cetak',
                    'Katalog Soft File & Cetak',
                    'Full Support CS Pusat',
                    'ID Card Digital',
                    'Kartu Nama',
                    'Bisa Menjual Paket Shafaq',
                    'Akses Database & Leads',
                    'Roll Banner Promosi',
                    'Acrylic Flyer Stand',
                    'Website Landing Page',
                    'Jaringan Kemitraan',
                    'Spanduk Kemitraan',
                    'Map Invoice HM Tour',
                    'Vest / Rompi HM',
                    'Bisa Buat Paket Customize',
                    'Hak Eksklusif Wilayah',
                    'Tools Marketing',
                    'Event Desk Meja Booth',
                    'Full Perlengkapan Display',
                    'Sistem Management',
                    'Pelatihan Operasional',
                    'Rekomendasi Tour Leader',
                    'Branding Design Kantor',
                    'Dukungan Iklan Berbayar',
                ]),
                'registration_fee' => 80000000,
                'min_sale_commission' => 2000000,
                'default_ppc_commission' => 50,
                'requires_previous_booking' => false,
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    public function down()
    {
        Schema::dropIfExists('partnership_programs');
    }
};
